service: ${self:custom.service}

custom:
  service: "serverless-boilerplate"
  stage: ${opt:stage, self:provider.stage}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: ${self:custom.table.user}
            sources: [./tools/migrate/users.json]
    stages:
      - LOCALDEV
  table:
    user: ${self:custom.service}-${self:custom.stage}-User
  serverless-offline-dynamodb-streams:
    apiVersion: "2013-12-02"
    endpoint: http://localhost:8000
    region: ap-northeast-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    readInterval: 500

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: DEV
  environment:
    SERVICE_NAME: ${self:custom.service}
    NODE_ENV: ${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        - { "Fn::GetAtt": ["UserTable", "Arn"] }
    - Effect: "Allow"
      Action:
        - "dynamodb:BatchWriteItem"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:DescribeStream"
        - "dynamodb:ListStreams"
      Resource:
        - { "Fn::GetAtt": ["UserTable", "StreamArn"] }

package:
  exclude:
    - .git/**
    - .nyc_output/**
    - coverage/**
    - test/**
    - package-lock.json

plugins:
  - serverless-dynamodb-local
  - serverless-offline-dynamodb-streams
  - serverless-offline

functions:
  app:
    handler: src/app.handler
    events:
      - http: "ANY /"
      - http: "ANY {proxy+}"
  stream:
    handler: src/stream.handler
    events:
      - stream:
          type: dynamodb
          enabled: true
          batchSize: 100
          startingPosition: TRIM_HORIZON
          arn: { "Fn::GetAtt": ["UserTable", "Arn"] }

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.user}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        SSESpecification:
          SSEEnabled: true
